export const AdminActionTypes = {
  LOAD_ADMIN: "LOAD_ADMIN",
  LOGOUT_ADMIN: "LOGOUT_ADMIN",
  GET_ALL_SUPPLIERS: "GET_ALL_SUPPLIERS",
  GET_ALL_USERS: "GET_ALL_USERS",
  VERIFY_SUPPLIER: "VERIFY_SUPPLIER",
  SUSPEND_SUPPLIER: "SUSPEND_SUPPLIER",
  VERIFY_USER: "VERIFY_USER",
  SUSPEND_USER: "SUSPEND_USER",

  ADMIN_START_LOAD_PRODUCT: "ADMIN_START_LOAD_PRODUCT",
  ADMIN_LOAD_PRODUCT_FAIL: "ADMIN_LOAD_PRODUCT_FAIL",
  ADMIN_LOAD_PRODUCT_SUCCESS: "ADMIN_LOAD_PRODUCT_SUCCESS",
  VERIFY_PRODUCT: "VERIFY_PRODUCT",

  ADMIN_START_LOAD_NOTIFICATION: "ADMIN_START_LOAD_NOTIFICATION",
  ADMIN_LOAD_NOTIFICATION_FAIL: "ADMIN_LOAD_NOTIFICATION_FAIL",
  ADMIN_LOAD_NOTIFICATION_SUCCESS: "ADMIN_LOAD_NOTIFICATION_SUCCESS",
  READ_NOTIFICATION: "READ_NOTIFICATION",

  ADMIN_START_LOAD_CATEGORY: "ADMIN_START_LOAD_CATEGORY",
  ADMIN_LOAD_CATEGORY_SUCCESS: "ADMIN_LOAD_CATEGORY_SUCCESS",

  ADMIN_START_LOAD_HELPS: "ADMIN_START_LOAD_HELPS",
  ADMIN_LOAD_HELPS_FAIL: "ADMIN_LOAD_HELP_FAIL",
  ADMIN_LOAD_HELPS_SUCCESS: "ADMIN_LOAD_HELPS_SUCCESS",
  READ_HELP: "READ_HELP",

  ADMIN_START_LOAD_PRESCRIPTIONS: "ADMIN_START_LOAD_PRESCRIPTIONS",
  ADMIN_LOAD_PRESCRIPTIONS_FAIL: "ADMIN_LOAD_PRESCRIPTIONS_FAIL",
  ADMIN_LOAD_PRESCRIPTIONS_SUCCESS: "ADMIN_LOAD_PRESCRIPTIONS_SUCCESS",
  RESPOND_TO_PRESCRIPTION: "RESPOND_TO_PRESCRIPTION",
};
