export const AdminActionTypes = {
    LOAD_ADMIN: "LOAD_ADMIN",
    LOGOUT_ADMIN: "LOGOUT_ADMIN",
    GET_ALL_SUPPLIERS: "GET_ALL_SUPPLIERS",
    VERIFY_SUPPLIER:"VERIFY_SUPPLIER",
    SUSPEND_SUPPLIER:"SUSPEND_SUPPLIER",

    ADMIN_START_LOAD_PRODUCT:"ADMIN_START_LOAD_PRODUCT",
    ADMIN_LOAD_PRODUCT_FAIL:"ADMIN_LOAD_PRODUCT_FAIL",
    ADMIN_LOAD_PRODUCT_SUCCESS:"ADMIN_LOAD_PRODUCT_SUCCESS",
    VERIFY_PRODUCT:"VERIFY_PRODUCT",

    ADMIN_START_LOAD_NOTIFICATION:"ADMIN_START_LOAD_NOTIFICATION",
    ADMIN_LOAD_NOTIFICATION_FAIL:"ADMIN_LOAD_NOTIFICATION_FAIL",
    ADMIN_LOAD_NOTIFICATION_SUCCESS:"ADMIN_LOAD_NOTIFICATION_SUCCESS",
    READ_NOTIFICATION:"READ_NOTIFICATION",

    ADMIN_START_LOAD_CATEGORY:"ADMIN_START_LOAD_CATEGORY",
    ADMIN_LOAD_CATEGORY_SUCCESS:"ADMIN_LOAD_CATEGORY_SUCCESS",
}