export const AdminActionTypes = {
    LOAD_ADMIN: "LOAD_ADMIN",
    LOGOUT_ADMIN: "LOGOUT_ADMIN",
    GET_ALL_SUPPLIERS: "GET_ALL_SUPPLIERS",
    VERIFY_SUPPLIER:"VERIFY_SUPPLIER",
    SUSPEND_SUPPLIER:"SUSPEND_SUPPLIER",
}