export const Regions = [
    { name: "ASHANTI" },
    { name: "BRONG AHAFO" },
    { name: "CENTRAL" },
    { name: "EASTERN" },
    { name: "GREATER ACCRA" },
    { name: "NORTHERN" },
    { name: "UPPER EAST" },
    { name: "UPPER WEST" },
    { name: "VOLTA" },
    { name: "WESTERN" },
  ];
  
  export const Constituencies = {
    ASHANTI: [
      { name: "Adansi Asokwa" },
      { name: "Afigya Sekyere East" },
      { name: "Afigya Sekyere West" },
      { name: "Ahafo-ano North" },
      { name: "Ahafo-ano South" },
      { name: "Akrofuom" },
      { name: "Amansie West" },
      { name: "Asante Akim South" },
      { name: "Asanti Akim North" },
      { name: "Asawase" },
      { name: "Asokwa" },
      { name: "Atwima-kwanwoma" },
      { name: "Atwima Mponua" },
      { name: "Atwima Nwabiagya" },
      { name: "Bantama" },
      { name: "Bekwai" },
      { name: "Bosome-freho" },
      { name: "Bosomtwe" },
      { name: "Effiduase Asokore" },
      { name: "Ejisu-juaben" },
      { name: "Ejura-sekyedumase" },
      { name: "Fomena" },
      { name: "Kumawu" },
      { name: "Kwabre East" },
      { name: "Kwabre West" },
      { name: "Kwadaso" },
      { name: "Mampong" },
      { name: "Manhyia" },
      { name: "New Edubiase" },
      { name: "Nhyiaeso" },
      { name: "Nsuta-kwamang Beposo" },
      { name: "Obuasi" },
      { name: "Odotobri" },
      { name: "Offinso South" },
      { name: "Offinsu North" },
      { name: "Oforikrom" },
      { name: "Old Tafo" },
      { name: "Suame" },
      { name: "Subin" },
    ],
    "BRONG AHAFO": [
      { name: "Asunafo North" },
      { name: "Asunafo South" },
      { name: "Asutifi North" },
      { name: "Asutifi South" },
      { name: "Atebubu/amantin" },
      { name: "Berekum" },
      { name: "Dormaa East" },
      { name: "Dormaa West" },
      { name: "Jaman North" },
      { name: "Jaman South" },
      { name: "Kintampo North" },
      { name: "Kintampo South" },
      { name: "Nkoranza North" },
      { name: "Nkoranza South" },
      { name: "Pru" },
      { name: "Sene" },
      { name: "Sunyani East" },
      { name: "Sunyani West" },
      { name: "Tain" },
      { name: "Tano North" },
      { name: "Tano South" },
      { name: "Techiman North" },
      { name: "Techiman South" },
      { name: "Wenchi" },
    ],
    CENTRAL: [
      { name: "Abura-asebu-kwamankese" },
      { name: "Agona East" },
      { name: "Agona West" },
      { name: "Ajumako-enyan-essiam" },
      { name: "Asikuma/odoben/brakwa" },
      { name: "Assin North" },
      { name: "Assin South" },
      { name: "Awutu-senya" },
      { name: "Cape Coast" },
      { name: "Effutu" },
      { name: "Gomoa East" },
      { name: "Gomoa West" },
      { name: "Hemang Lower Denkyira" },
      { name: "Komenda-edina Eguafo-abirem" },
      { name: "Mfantsiman East" },
      { name: "Mfantsiman West" },
      { name: "Twifu-esti/morkwaa" },
      { name: "Upper Denkyira East" },
      { name: "Upper Denkyira West" },
    ],
    EASTERN: [
      { name: "Abetifi" },
      { name: "Abirem" },
      { name: "Aburi-nsawam" },
      { name: "Afram Plains North" },
      { name: "Afram Plains South" },
      { name: "Akim Abuakwa North" },
      { name: "Akim Abuakwa South" },
      { name: "Akim Oda" },
      { name: "Akim Swedru" },
      { name: "Akropong" },
      { name: "Akwatia" },
      { name: "Asuogyaman" },
      { name: "Atiwa" },
      { name: "Ayesuano" },
      { name: "Fanteakwa" },
      { name: "Kade" },
      { name: "Lower Manya" },
      { name: "Lower/west Akim" },
      { name: "Mpraeso" },
      { name: "New Juaben North" },
      { name: "New Juaben South" },
      { name: "Nkawkaw" },
      { name: "Ofoase/ayerebi" },
      { name: "Okere" },
      { name: "Suhum" },
      { name: "Upper Manya" },
      { name: "Upper/west Akim" },
      { name: "Yilo Krobo" },
    ],
    "GREATER ACCRA": [
      { name: "Ablekuma Central" },
      { name: "Ablekuma North" },
      { name: "Ablekuma South" },
      { name: "Abokobi/madina" },
      { name: "Ada" },
      { name: "Adenta" },
      { name: "Ashiaman" },
      { name: "Ayawaso Central" },
      { name: "Ayawaso East" },
      { name: "Ayawaso West Wuogon" },
      { name: "Dade-kotopon" },
      { name: "Domeabra-obom" },
      { name: "Dome/kwabenya" },
      { name: "Klottey-korle" },
      { name: "Kpone-katamanso" },
      { name: "Krowor" },
      { name: "Ledzokuku" },
      { name: "Ningo-prampram" },
      { name: "Odododiodioo" },
      { name: "Okaikwei North" },
      { name: "Okaikwei South" },
      { name: "Sege" },
      { name: "Shai-osudoku" },
      { name: "Tema East" },
      { name: "Tema West" },
      { name: "Tro-bu/amasaman" },
      { name: "Weija" },
    ],
    NORTHERN: [
      { name: "Bimbilla" },
      { name: "Bole" },
      { name: "Bunkpurugu" },
      { name: "Chereponi" },
      { name: "Damongo/daboya" },
      { name: "Gushiegu" },
      { name: "Karaga" },
      { name: "Kpandai" },
      { name: "Kumbungu" },
      { name: "Mion" },
      { name: "Nalerigu" },
      { name: "Nanton" },
      { name: "Saboba" },
      { name: "Salaga" },
      { name: "Savelugu" },
      { name: "Sawla/kalba" },
      { name: "Tamale Central" },
      { name: "Tamale North" },
      { name: "Tamale South" },
      { name: "Tolon" },
      { name: "Walewale" },
      { name: "Wulensi" },
      { name: "Yagaba" },
      { name: "Yapei/kusawgu" },
      { name: "Yendi" },
      { name: "Zabzugu/tatale" },
    ],
    "UPPER EAST": [
      { name: "Bawku" },
      { name: "Binduri" },
      { name: "Bolgatanga" },
      { name: "Bongo" },
      { name: "Builsa North" },
      { name: "Builsa South" },
      { name: "Chiana/paga" },
      { name: "Garu/tempane" },
      { name: "Nabdam" },
      { name: "Navrongo" },
      { name: "Pusiga" },
      { name: "Talensi" },
      { name: "Zebilla" },
    ],
    "UPPER WEST": [
      { name: "Jirapa" },
      { name: "Lamussie" },
      { name: "Lawra" },
      { name: "Nadowli East" },
      { name: "Nadowli West" },
      { name: "Sissala East" },
      { name: "Sissala West" },
      { name: "Wa Central" },
      { name: "Wa East" },
      { name: "Wa West" },
    ],
    VOLTA: [
      { name: "Adaklu-anyigbe" },
      { name: "Akan" },
      { name: "Anlo" },
      { name: "Avenor" },
      { name: "Biakoye" },
      { name: "Buem" },
      { name: "Central Tongu" },
      { name: "Ho Central" },
      { name: "Hohoe North" },
      { name: "Hohoe South" },
      { name: "Ho West" },
      { name: "Keta" },
      { name: "Ketu North" },
      { name: "Ketu South" },
      { name: "Krachi East" },
      { name: "Krachi West" },
      { name: "Nkwanta North" },
      { name: "Nkwanta South" },
      { name: "North Dayi" },
      { name: "North Tongu" },
      { name: "South Dayi" },
      { name: "South Tongu" },
    ],
    WESTERN: [
      { name: "Ahanta West" },
      { name: "Amenfi Central" },
      { name: "Amenfi East" },
      { name: "Amenfi West" },
      { name: "Aowin" },
      { name: "Bia" },
      { name: "Bibiani-anhwiaso-bekwai" },
      { name: "Effia-kwesimintsim" },
      { name: "Ellembelle" },
      { name: "Essikadu-ketan" },
      { name: "Evalue-gwira" },
      { name: "Jomoro" },
      { name: "Juaboso" },
      { name: "Mpohor-wassa East" },
      { name: "Prestea-hunivalley" },
      { name: "Sefwi Akontombra" },
      { name: "Sefwi-wiawso" },
      { name: "Sekondi" },
      { name: "Shama" },
      { name: "Suaman" },
      { name: "Takoradi" },
      { name: "Tarkwa/nsuaem" },
    ],
  };
  