export const SupplierActionTypes = {
    LOAD_SUPPLIER: "LOAD_SUPPLIER",
    LOGOUT_SUPPLIER: "LOGOUT_SUPPLIER",
    SUPPLIER_UPLOAD_PRODUCT:"SUPPLIER_UPLOAD_PRODUCT",
    
    
    SUPPLIER_UPLOAD_ADDITIONAL_IMAGES:"SUPPLIER_UPLOAD_ADDITIONAL_IMAGES",
    SUPPLIER_DELETE_PRODUCT_IMAGE:"SUPPLIER_DELETE_PRODUCT_IMAGE",
    SUPPLIER_EDIT_PRODUCT_IMAGE:"SUPPLIER_EDIT_PRODUCT_IMAGE",
    SUPPLIER_UPDATE_PRODUCT:"SUPPLIER_UPDATE_PRODUCT",
   
   
    SUPPLIER_START_LOAD_PRODUCT:"SUPPLIER_START_LOAD_PRODUCT",
    SUPPLIER_LOAD_PRODUCT_FAIL:"SUPPLIER_LOAD_PRODUCT_FAIL",
    SUPPLIER_LOAD_PRODUCT_SUCCESS:"SUPPLIER_LOAD_PRODUCT_SUCCESS",

    SUPPLIER_START_LOAD_NOTIFICATION:"SUPPLIER_START_LOAD_NOTIFICATION",
    SUPPLIER_LOAD_NOTIFICATION_FAIL:"SUPPLIER_LOAD_NOTIFICATION_FAIL",
    SUPPLIER_LOAD_NOTIFICATION_SUCCESS:"SUPPLIER_LOAD_NOTIFICATION_SUCCESS",
    READ_NOTIFICATION:"READ_NOTIFICATION",
    
}